export const SET_NUMBER = "SET_NUMBER";
export const SET_OPERATOR = "SET_OPERATOR";

export const ADD_DECIMAL = "ADD_DECIMAL";
export const DELETE_ENTRY = "DELETE_ENTRY";

export const RESET_CALCULATOR = "RESET_CALCULATOR";
export const GET_RESULT = "GET_RESULT";

export const CONTINUE_AFTER_RESULT = "CONTINUE_AFTER_RESULT";

export const SET_THEME = "SET_THEME";
